import { Button } from "@chakra-ui/button";
import { useColorMode } from "@chakra-ui/color-mode";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Button onClick={toggleColorMode}>
          Toggle {colorMode === "light" ? "Dark" : "Light"}
        </Button>
      </header>
    </div>
  );
};

export default Home;
